### Signup
POST https://cloudwallet-solana.onrender.com/api/v1/signup
Content-Type: application/json

{
  "username": "testuser11",
  "password": "testpass11",
  "email": "test11@example.com"
}

### Signin
POST https://cloudwallet-solana.onrender.com/api/v1/signin
Content-Type: application/json

{
  "username": "testuser1",
  "password": "testpass1"
}

### Send Transaction
POST https://cloudwallet-solana.onrender.com/api/v1/txn/sign
Content-Type: application/json
Authorization: Bearer <YOUR_JWT_TOKEN_HERE>

{
  "toAddress": "HoomsS5YfyNP2icfW44zh84VqT8v6AWHS8amurMJBXcE",
  "amount": 0.01
}